sudo: false
dist: trusty

git:
  submodules: false

language: c

services:
- docker

branches:
  only:
  - master

env:
  global:
    - TIZENRT_IMG_VERSION=latest
  
before_install:
- docker pull tizenrt/tizenrt:${TIZENRT_IMG_VERSION}
- echo "${TRAVIS_BUILD_DIR}"

script:
- docker run -d -it --name tizenrt_docker -v ${TRAVIS_BUILD_DIR}:/root/tizenrt -w /root/tizenrt/os --privileged tizenrt/tizenrt:${TIZENRT_IMG_VERSION} /bin/bash
- docker exec tizenrt_docker arm-none-eabi-gcc --version

- docker exec -it tizenrt_docker bash -c "./tools/build_test.sh"
